### ISSUE TITLE
Not able to generate thedata using sample.csv

### ISSUE THREAD

**Issue by nithinb** [microsoft/anomalydetector#26]
Earlier when I used to run the following command (`python3 srcnn/generate_data.py samples/sample.csv`) it used the process the data as desired and the entire code used to work without an issue. But currently I get the following error and I am not sure if this is a bug or something that I messed up

>python3 srcnn/generate_data.py samples/sample.csv
Traceback (most recent call last):
  File "srcnn/generate_data.py", line 28, in <module>
    from srcnn.utils import *
ModuleNotFoundError: No module named 'srcnn'

Kindly advice. And thanks in advance 😄

**Comment by rishikesan-vunet** [comment]
> Earlier when I used to run the following command (`python3 srcnn/generate_data.py samples/sample.csv`) it used the process the data as desired and the entire code used to work without an issue. But currently I get the following error and I am not sure if this is a bug or something that I messed up
> 
> > python3 srcnn/generate_data.py samples/sample.csv
> > Traceback (most recent call last):
> > File "srcnn/generate_data.py", line 28, in 
> > from srcnn.utils import *
> > ModuleNotFoundError: No module named 'srcnn'
> 
> Kindly advice. And thanks in advance

I am getting the same error. How to solve this?

**Comment by seaman1900** [comment]
you should append this code before from srcnn.utils import *
import sys
sys.path.append('../')

**Comment by aquirin-te** [comment]
See here: https://github.com/microsoft/anomalydetector/issues/29

Then, it seems the CSV should be in a subfolder, ie, instead of `samples/sample.csv`, it should be here : `samples/sample/sample.csv`

Then it is possible to run: `python3 srcnn/generate_data.py anomalydetector.git/samples`
